BEGIN
  FOR rec IN (SELECT object_name, object_type FROM user_objects 
              WHERE object_type IN ('TABLE') AND object_name IN 
              ('AUDITLOG', 'TRANSACTIONS', 'LOANS', 'ACCOUNTS', 'EMPLOYEES', 'CUSTOMERS')) LOOP
    EXECUTE IMMEDIATE 'DROP ' || rec.object_type || ' "' || rec.object_name || '"';
  END LOOP;
END;
/

-- Customers
CREATE TABLE Customers (
  CustomerID NUMBER PRIMARY KEY,
  Name VARCHAR2(100),
  DOB DATE,
  Balance NUMBER,
  LastModified DATE
);

-- Accounts
CREATE TABLE Accounts (
  AccountID NUMBER PRIMARY KEY,
  CustomerID NUMBER,
  AccountType VARCHAR2(20),
  Balance NUMBER,
  CreatedDate DATE,
  FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

-- Loans
CREATE TABLE Loans (
  LoanID NUMBER PRIMARY KEY,
  CustomerID NUMBER,
  InterestRate NUMBER,
  EndDate DATE,
  FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

-- Employees
CREATE TABLE Employees (
  EmployeeID NUMBER PRIMARY KEY,
  Name VARCHAR2(100),
  Position VARCHAR2(50),
  Salary NUMBER,
  Department VARCHAR2(50),
  JoinedDate DATE
);

-- Transactions
CREATE TABLE Transactions (
  TransactionID NUMBER PRIMARY KEY,
  AccountID NUMBER,
  TransactionType VARCHAR2(20),
  Amount NUMBER,
  TransactionDate DATE,
  FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID)
);

-- Audit Log
CREATE TABLE AuditLog (
  LogID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  Action VARCHAR2(100),
  LogDate DATE
);

-- Insert Customers
INSERT INTO Customers VALUES (1, 'Alice', TO_DATE('1960-05-10','YYYY-MM-DD'), 15000, SYSDATE);
INSERT INTO Customers VALUES (2, 'Bob', TO_DATE('1990-01-01','YYYY-MM-DD'), 9000, SYSDATE);
INSERT INTO Customers VALUES (3, 'Charlie', TO_DATE('1985-03-15','YYYY-MM-DD'), 5000, SYSDATE);

-- Insert Accounts
INSERT INTO Accounts VALUES (101, 1, 'Savings', 20000, SYSDATE);
INSERT INTO Accounts VALUES (102, 2, 'Current', 5000, SYSDATE);
INSERT INTO Accounts VALUES (103, 3, 'Savings', 12000, SYSDATE);

-- Insert Loans
INSERT INTO Loans VALUES (201, 1, 7.5, SYSDATE + 15);
INSERT INTO Loans VALUES (202, 2, 8.0, SYSDATE + 45);
INSERT INTO Loans VALUES (203, 3, 9.0, SYSDATE + 25);

-- Insert Employees
INSERT INTO Employees VALUES (301, 'John', 'Manager', 70000, 'Finance', SYSDATE);
INSERT INTO Employees VALUES (302, 'Emma', 'Developer', 50000, 'IT', SYSDATE);
INSERT INTO Employees VALUES (303, 'Steve', 'Clerk', 30000, 'HR', SYSDATE);

-- Insert Transactions
INSERT INTO Transactions VALUES (1, 101, 'Deposit', 1000, SYSDATE);
INSERT INTO Transactions VALUES (2, 102, 'Withdrawal', 500, SYSDATE);
INSERT INTO Transactions VALUES (3, 103, 'Deposit', 1200, SYSDATE);

-- ✅ Tables and sample data now safely reset with no duplicates
select  * from  Customers;
select  * from Accounts;
select  * from Loans;
select  * from Employees;
select  * from Transactions;


